### ISSUE TITLE
How to run the Example by swift run?

### ISSUE THREAD

**Issue by felixf4xu** [OpenSwiftUIProject/OpenSwiftUI#23]
Hi,

I can successfully run `swift build` for the project, but when I run `swift run`, 
>error: no executable product available

How can I run the examples?

Ubuntu 22, without Xcode.

**Comment by Kyle-Ye** [comment]
1. The example is currently written as a xcodeproj(macOS and iOS with Xcode is required) instead of a package so you can't run it on Linux platform. SwiftPM entry executable point only supports macOS and Linux. I'll update the example to add a SwiftPM based example package later to support Linux platform `swift run`
2. The project is still in early development, so only some interface API and underlying data structure is supported. So you can't boot and show an UI element yet.
